#!/usr/bin/env python3
"""
synthetic_indexer.py - 0-Token Deterministic Barrel & Router Indexer (v8.0)
Supports:
1. Component / Service Barrel Generation:
   python synthetic_indexer.py client/src/components
2. Pluggable Express / Hono API Router Assembly:
   python synthetic_indexer.py --routes server/src/routes
"""

import os
import sys

def generate_barrel(directory, output_file=None):
    if not os.path.exists(directory):
        print(f"Directory {directory} does not exist. Skipping.")
        return
        
    files = [f for f in os.listdir(directory) if f.endswith(('.tsx', '.ts', '.jsx', '.js')) and not f.startswith(('index.', '_'))]
    if not files:
        print(f"No component/route files found in {directory}.")
        return

    exports = []
    for file in sorted(files):
        name = os.path.splitext(file)[0]
        exports.append(f"export * from './{name}';")

    content = "// Auto-generated by CEST Synthetic Indexer (v8.0)\n" + "\n".join(exports) + "\n"
    
    if output_file is None:
        ext = ".ts" if any(f.endswith(('.ts', '.tsx')) for f in files) else ".js"
        output_file = os.path.join(directory, f"index{ext}")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"✅ Generated synthetic barrel index: {output_file} ({len(files)} exports)")

def generate_router_index(directory, output_file=None):
    if not os.path.exists(directory):
        print(f"Directory {directory} does not exist. Skipping.")
        return

    files = [f for f in os.listdir(directory) if f.endswith(('.ts', '.js')) and not f.startswith(('index.', '_'))]
    if not files:
        print(f"No route handler files found in {directory}.")
        return

    imports = ["import { Router } from 'express';"]
    mounts = ["export const apiRouter = Router();\n"]

    for file in sorted(files):
        name = os.path.splitext(file)[0]
        # Clean route name: auth.routes.ts -> auth, products.ts -> products
        clean_name = name.replace(".routes", "").replace("-routes", "")
        identifier = f"{clean_name}Routes"
        imports.append(f"import {identifier} from './{name}';")
        mounts.append(f"apiRouter.use('/{clean_name}', {identifier});")

    mounts.append("\nexport default apiRouter;\n")
    content = "// Auto-generated by CEST Synthetic Indexer (v8.0)\n" + "\n".join(imports) + "\n\n" + "\n".join(mounts)

    if output_file is None:
        ext = ".ts" if any(f.endswith('.ts') for f in files) else ".js"
        output_file = os.path.join(directory, f"index{ext}")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"✅ Generated synthetic Express API router: {output_file} ({len(files)} route modules)")

if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        print("Usage: python synthetic_indexer.py [--routes] <directory> [output_file]")
        sys.exit(1)

    if args[0] == "--routes":
        if len(args) < 2:
            print("Usage: python synthetic_indexer.py --routes <directory> [output_file]")
            sys.exit(1)
        out = args[2] if len(args) > 2 else None
        generate_router_index(args[1], out)
    else:
        out = args[1] if len(args) > 1 else None
        generate_barrel(args[0], out)
