import os
import sys

def generate_barrel(directory, output_file=None):
    if not os.path.exists(directory):
        print(f"Directory {directory} does not exist. Skipping.")
        return
        
    files = [f for f in os.listdir(directory) if f.endswith(('.tsx', '.ts', '.jsx', '.js')) and not f.startswith(('index.', '_'))]
    if not files:
        print(f"No component/route files found in {directory}.")
        return

    exports = []
    for file in sorted(files):
        name = os.path.splitext(file)[0]
        exports.append(f"export * from './{name}';")

    content = "// Auto-generated by CEST Synthetic Indexer (v8.0)\n" + "\n".join(exports) + "\n"
    
    if output_file is None:
        ext = ".ts" if any(f.endswith(('.ts', '.tsx')) for f in files) else ".js"
        output_file = os.path.join(directory, f"index{ext}")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"✅ Generated synthetic barrel index: {output_file} ({len(files)} exports)")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python synthetic_indexer.py <directory> [output_file]")
        sys.exit(1)
        
    out = sys.argv[2] if len(sys.argv) > 2 else None
    generate_barrel(sys.argv[1], out)
