const fs = require('fs');
const path = require('path');

function generateBarrel(directory, outputFile) {
    if (!fs.existsSync(directory)) {
        console.log(`Directory ${directory} does not exist. Skipping.`);
        return;
    }

    const files = fs.readdirSync(directory).filter(f => 
        (f.endsWith('.tsx') || f.endsWith('.ts') || f.endsWith('.jsx') || f.endsWith('.js')) &&
        !f.startsWith('index.') && !f.startsWith('_')
    );

    if (files.length === 0) {
        console.log(`No component/route files found in ${directory}.`);
        return;
    }

    const exports = files.sort().map(f => {
        const name = path.parse(f).name;
        return `export * from './${name}';`;
    });

    const content = "// Auto-generated by CEST Synthetic Indexer (v8.0)\n" + exports.join('\n') + '\n';
    
    if (!outputFile) {
        const ext = files.some(f => f.endsWith('.ts') || f.endsWith('.tsx')) ? '.ts' : '.js';
        outputFile = path.join(directory, `index${ext}`);
    }

    fs.writeFileSync(outputFile, content, 'utf-8');
    console.log(`✅ Generated synthetic barrel index: ${outputFile} (${files.length} exports)`);
}

const args = process.argv.slice(2);
if (args.length < 1) {
    console.error('Usage: node synthetic_indexer.js <directory> [output_file]');
    process.exit(1);
}

generateBarrel(args[0], args[1]);
