#!/usr/bin/env node
/**
 * synthetic_indexer.js - 0-Token Deterministic Barrel & Router Indexer (v8.0)
 * Supports:
 * 1. Component / Service Barrel Generation:
 *    node synthetic_indexer.js client/src/components
 * 2. Pluggable Express / Hono API Router Assembly:
 *    node synthetic_indexer.js --routes server/src/routes
 */

const fs = require('fs');
const path = require('path');

function generateBarrel(directory, outputFile) {
    if (!fs.existsSync(directory)) {
        console.log(`Directory ${directory} does not exist. Skipping.`);
        return;
    }

    const files = fs.readdirSync(directory).filter(f => 
        (f.endsWith('.tsx') || f.endsWith('.ts') || f.endsWith('.jsx') || f.endsWith('.js')) &&
        !f.startsWith('index.') && !f.startsWith('_')
    );

    if (files.length === 0) {
        console.log(`No component/route files found in ${directory}.`);
        return;
    }

    const exports = files.sort().map(f => {
        const name = path.parse(f).name;
        return `export * from './${name}';`;
    });

    const content = "// Auto-generated by CEST Synthetic Indexer (v8.0)\n" + exports.join('\n') + '\n';
    
    if (!outputFile) {
        const ext = files.some(f => f.endsWith('.ts') || f.endsWith('.tsx')) ? '.ts' : '.js';
        outputFile = path.join(directory, `index${ext}`);
    }

    fs.writeFileSync(outputFile, content, 'utf-8');
    console.log(`✅ Generated synthetic barrel index: ${outputFile} (${files.length} exports)`);
}

function generateRouterIndex(directory, outputFile) {
    if (!fs.existsSync(directory)) {
        console.log(`Directory ${directory} does not exist. Skipping.`);
        return;
    }

    const files = fs.readdirSync(directory).filter(f =>
        (f.endsWith('.ts') || f.endsWith('.js')) &&
        !f.startsWith('index.') && !f.startsWith('_')
    );

    if (files.length === 0) {
        console.log(`No route handler files found in ${directory}.`);
        return;
    }

    const imports = ["import { Router } from 'express';"];
    const mounts = ["export const apiRouter = Router();\n"];

    files.sort().forEach(f => {
        const name = path.parse(f).name;
        const cleanName = name.replace('.routes', '').replace('-routes', '');
        const identifier = `${cleanName}Routes`;
        imports.push(`import ${identifier} from './${name}';`);
        mounts.push(`apiRouter.use('/${cleanName}', ${identifier});`);
    });

    mounts.push("\nexport default apiRouter;\n");
    const content = "// Auto-generated by CEST Synthetic Indexer (v8.0)\n" + imports.join('\n') + '\n\n' + mounts.join('\n');

    if (!outputFile) {
        const ext = files.some(f => f.endsWith('.ts')) ? '.ts' : '.js';
        outputFile = path.join(directory, `index${ext}`);
    }

    fs.writeFileSync(outputFile, content, 'utf-8');
    console.log(`✅ Generated synthetic Express API router: ${outputFile} (${files.length} route modules)`);
}

const args = process.argv.slice(2);
if (args.length < 1) {
    console.error('Usage: node synthetic_indexer.js [--routes] <directory> [output_file]');
    process.exit(1);
}

if (args[0] === '--routes') {
    if (args.length < 2) {
        console.error('Usage: node synthetic_indexer.js --routes <directory> [output_file]');
        process.exit(1);
    }
    generateRouterIndex(args[1], args[2]);
} else {
    generateBarrel(args[0], args[1]);
}
